export const GET_EXPERIENCES_REQUEST = "EXPERIENCE.GET_EXPERIENCES_REQUEST";
export const GET_EXPERIENCES_SUCCESS = "EXPERIENCE.GET_EXPERIENCES_SUCCESS";
export const GET_EXPERIENCES_FAILURE = "EXPERIENCE.GET_EXPERIENCES_FAILURE";
